export const cards = [
  { title: "Podcasts", color: "bg-emerald-600", img: "/cards/podcast.svg" },
  { title: "For You", color: "bg-indigo-700", img: "/cards/forYou.svg" },
  { title: "Charts", color: "bg-violet-700", img: "/cards/charts.svg" },
  { title: "New Releases", color: "bg-rose-600", img: "/cards/newReleases.svg" },
  { title: "Discover", color: "bg-indigo-500", img: "/cards/discover.svg" },
  { title: "Concerts", color: "bg-blue-950", img: "/cards/content.svg" },
  { title: "R&B", color: "bg-rose-500", img: "/cards/R&B.svg" },
  { title: "Frequency", color: "bg-neutral-600", img: "/cards/frequency.svg" },
  { title: "Christian & Gospel", color: "bg-sky-500", img: "/cards/christian&gospel.svg" },
  { title: "Soul", color: "bg-fuchsia-700", img: "/cards/soul.svg" },
  { title: "Chill", color: "bg-cyan-200", img: "/cards/chill.svg" },
  { title: "Mood", color: "bg-purple-300", img: "/cards/mood.svg" },
  { title: "Equal", color: "bg-lime-500", img: "/cards/equal.svg" },
  { title: "Alternative", color: "bg-teal-400", img: "/cards/alternative.svg" },
  { title: "Workout", color: "bg-gray-700", img: "/cards/workout.svg" },
  { title: "Party", color: "bg-pink-500", img: "/cards/party.svg" },
  { title: "Pop", color: "bg-purple-500", img: "/cards/pop.svg" },
  { title: "Hip-Hop", color: "bg-orange-600", img: "/cards/hipHop.svg" },
  { title: "Afro", color: "bg-rose-600", img: "/cards/afro.svg" },
  { title: "Rewind", color: "bg-blue-500", img: "/cards/rewind.svg" },
];
