export const genres = [
  { title: "Podcasts", color: "bg-emerald-600", img: "/genres/podcast.svg" },
  { title: "For You", color: "bg-indigo-700", img: "/genres/forYou.svg" },
  { title: "Charts", color: "bg-violet-700", img: "/genres/charts.svg" },
  { title: "New Releases", color: "bg-rose-600", img: "/genres/newReleases.svg" },
  { title: "Discover", color: "bg-indigo-500", img: "/genres/discover.svg" },
  { title: "Concerts", color: "bg-blue-950", img: "/genres/content.svg" },
  { title: "R&B", color: "bg-rose-500", img: "/genres/R&B.svg" },
  { title: "Frequency", color: "bg-neutral-600", img: "/genres/frequency.svg" },
  { title: "Christian & Gospel", color: "bg-sky-500", img: "/genres/christian&gospel.svg" },
  { title: "Soul", color: "bg-fuchsia-700", img: "/genres/soul.svg" },
  { title: "Chill", color: "bg-cyan-200", img: "/genres/chill.svg" },
  { title: "Mood", color: "bg-purple-300", img: "/genres/mood.svg" },
  { title: "Equal", color: "bg-lime-500", img: "/genres/equal.svg" },
  { title: "Alternative", color: "bg-teal-400", img: "/genres/alternative.svg" },
  { title: "Workout", color: "bg-gray-700", img: "/genres/workout.svg" },
  { title: "Party", color: "bg-pink-500", img: "/genres/party.svg" },
  { title: "Pop", color: "bg-purple-500", img: "/genres/pop.svg" },
  { title: "Hip-Hop", color: "bg-orange-600", img: "/genres/hipHop.svg" },
  { title: "Afro", color: "bg-rose-600", img: "/genres/afro.svg" },
  { title: "Rewind", color: "bg-blue-500", img: "/genres/rewind.svg" },
];
